# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [5]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(size=(7, 7))
random_tensor, random_tensor.shape


(tensor([[0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783],
         [0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
random_tensor_2 = random_tensor
random_tensor_3 = torch.rand(size=(1, 7))
print(f"题目2中的张量为：\n {random_tensor_2, random_tensor_2.shape} \n")
print(f"形状为(1, 7)形状的张量为: \n {random_tensor_3, random_tensor_3.shape}\n")

# Perform matrix multiplication 
tensors_mul = torch.matmul(random_tensor_2, random_tensor_3.T) # 别忘了内部维度匹配，所以需要转置
print(f"两个张量的乘积为：\n{tensors_mul, tensors_mul.shape}")

题目2中的张量为：
 (tensor([[0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783],
        [0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]), torch.Size([7, 7])) 

形状为(1, 7)形状的张量为: 
 (tensor([[0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038]]), torch.Size([1, 7]))

两个张量的乘积为：
(tensor([[1.1061],
        [0.9868],
        [1.8999],
        [0.7716],
        [1.3174],
        [1.6353],
        [1.7395]]), torch.Size([7, 1]))


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
tensor_seed_2 = torch.rand(size=(7, 7))
print(f"设置种子之后的张量2：\n{tensor_seed_2, tensor_seed_2.shape}\n")

torch.manual_seed(RANDOM_SEED)
tensor_seed_3 = torch.rand(size=(1, 7))
print(f"设置种子之后的张量3：\n{tensor_seed_3, tensor_seed_3.shape}\n")

# Matrix multiply tensors
tensor_seed_mul = torch.matmul(tensor_seed_2, tensor_seed_3.T)
print(f"打印结果: \n{tensor_seed_mul, tensor_seed_mul.shape}")

设置种子之后的张量2：
(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]), torch.Size([7, 7]))

设置种子之后的张量3：
(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]), torch.Size([1, 7]))

打印结果: 
(tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]]), torch.Size([7, 1]))


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
RANDOM_SEED_GPU = 1234
torch.cuda.manual_seed(RANDOM_SEED_GPU)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [9]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"设备：{device}")

# Create two random tensors on GPU
tensor_A_gpu = torch.rand(size=(2, 3)).to(device)
tensor_B_gpu = torch.rand(size=(2, 3)).to(device)

tensor_A_gpu, tensor_B_gpu



设备：cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [10]:
# Perform matmul on tensor_A and tensor_B
tensor_gpu_mul = torch.matmul(tensor_A_gpu, tensor_B_gpu.T)
print(f"在GPU上计算的矩阵乘法的乘积为：\n {tensor_gpu_mul, tensor_gpu_mul.shape}")

在GPU上计算的矩阵乘法的乘积为：
 (tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))


### 8. Find the maximum and minimum values of the output of 7.

In [13]:
# Find max
tensor_gpu_mul_max = torch.max(tensor_gpu_mul)
# Find min
tensor_gpu_mul_min = torch.min(tensor_gpu_mul)

print(f"最大值为：{tensor_gpu_mul_max}")
print(f"最小值为：{tensor_gpu_mul_min}")


最大值为：0.5617256760597229
最小值为：0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [12]:
# Find arg max
tensor_gpu_mul_max_index = tensor_gpu_mul.argmax()
print(f"最大值索引位置为：\n{tensor_gpu_mul_max_index}\n")

# Find arg min
tensor_gpu_mul_min_index = tensor_gpu_mul.argmin()
print(f"最小值索引位置为：\n{tensor_gpu_mul_min_index}")

最大值索引位置为：
3

最小值索引位置为：
0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [14]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_dim4 = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_dim4_remv_1 = tensor_dim4.squeeze()

# Print out tensors and their shapes
print(f"向量1及其形状：{tensor_dim4, tensor_dim4.shape}")
print(f"向量2及其形状：{tensor_dim4_remv_1, tensor_dim4_remv_1.shape}")

向量1及其形状：(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10]))
向量2及其形状：(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), torch.Size([10]))
